# Server Configuration

server.port=8080

# PostgreSQL Configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/urban_black
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANT (Fix for Hibernate Dialect Error)

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration

urbanblack.jwt.secret=9a67471ec97aa3d01bd8ec5e7f1c1f7cedda4b6f1234567890abcdef
urbanblack.jwt.expiration=86400000

# File Upload Configuration

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
upload.path=./uploads

# Razorpay Configuration
razorpay.key.id=rzp_test_SQbnlhk9jtL3LE
razorpay.key.secret=ACa6wNscxnibfzWt2DtQA7PV

# Cloudinary Configuration
cloudinary.cloud_name=dsi7apgoy
cloudinary.api_key=245776615689864
cloudinary.api_secret=PMy-wICsW42R_hvLLSz467e3I1Q
